In [11]:
#* ----------------------------------------------------------------------------------
#*  Note: Options data is an input file here as both CSV as well as Scraped from
#* .    the option site of Yahoo screen!                                                                  -
#* 1. Report on all OUTPUT CSV files from prior SQL runs                            -
#* 2. Using sqlalchemy, load an ETL to SQL_PG_Admin                                 -
#* 3. Link PANDAS-PYTHON to the SQL database, that includes Stocks & Options Data.  -
#* 4. Load the data for future use                                      -
#* 5. Ensure Password used to access DB:ALEMIDEPT is not passed to github           -
#* 6. Create MPLOT Charts on some of the outputs, to provide a visual report        -
#*                                                                 -
#* -                                                        Piruz Alemi, Jan 31 2020 -
#* ----------------------------------------------------------------------------------

In [12]:
# SQLAlchemy
from sqlalchemy import create_engine

In [13]:
# . Parses a Paasword
# . Perhaps! it should be placed in a config file that is placed in .ignore
import urllib.parse
urllib.parse.quote_plus("Roshan$$0*7")

'Roshan%24%240%2A7'

In [14]:
# import output CSV files of SQL runs into Pandas_Python program
# Note to the reader: These CSV files are output files of SQL runs under PgAdmin
import pandas as pd
import os
pd.read_csv("../ETL_Challenge/spy.csv")
# Report #1: Employees Report by Dept Name.
#            . This and other subsequents reports were originally created by Alemi
#            in SQL under PgAdmin

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-01-29,263.920013,264.549988,262.480011,263.410004,258.514801,66136300
1,2019-01-30,265.100006,268.519989,264.250000,267.579987,262.607300,92473700
2,2019-01-31,267.510010,270.470001,267.269989,269.929993,264.913605,104012100
3,2019-02-01,270.149994,271.200012,269.179993,270.059998,265.041229,85782500
4,2019-02-04,270.109985,272.029999,269.359985,271.959991,266.905884,60744800
...,...,...,...,...,...,...,...
247,2020-01-22,332.239990,332.950012,331.170013,331.339996,331.339996,48914900
248,2020-01-23,330.630005,332.170013,329.410004,331.720001,331.720001,51963000
249,2020-01-24,332.440002,332.529999,327.359985,328.769989,328.769989,87578400
250,2020-01-27,323.029999,325.119995,322.660004,323.500000,323.500000,83877900
251,2020-01-28,325.059998,327.839996,323.603790,326.880005,326.880005,63833953

In [15]:
pd.read_csv("../etl_Challenge/options_data.csv")
# Report #1b: List of employees and their salaries

,Contract Name,Bid,Strike,Last Price,Last Trade Date,Implied Volatility,DateTime
0,SPY200129C00280000,47.87,280.0,42.65,2020-01-06 12:15PM EST,135.16%,2020-01-06 12:15PM EST
1,SPY200129C00300000,27.92,300.0,27.00,2020-01-27 3:42PM EST,83.20%,2020-01-27 3:42PM EST
2,SPY200129C00301000,26.93,301.0,22.96,2020-01-27 3:41PM EST,81.84%,2020-01-27 3:41PM EST
3,SPY200129C00302000,25.93,302.0,26.40,2020-01-10 9:37AM EST,78.52%,2020-01-10 9:37AM EST
4,SPY200129C00303000,24.92,303.0,23.84,2020-01-28 1:05PM EST,75.39%,2020-01-28 1:05PM EST
...,...,...,...,...,...,...,...
162,SPY200131C00350000,0.00,350.0,0.01,2020-01-27 1:46PM EST,50.00%,2020-01-27 1:46PM EST
163,SPY200131C00352500,0.00,352.5,0.02,2019-12-30 11:08AM EST,53.13%,2019-12-30 11:08AM EST
164,SPY200131C00355000,0.00,355.0,0.01,2020-01-16 2:07PM EST,57.81%,2020-01-16 2:07PM EST
165,SPY200131C00365000,-,365.0,0.01,2020-01-30 3:51PM EST,79.69%,2020-01-30 3:51PM EST
166,SPY200131C00370000,-,370.0,0.01,2020-01-30 11:05PM EST,87.50%,2020-01-30 11:05PM EST

In [16]:
# Path to sqlite
database_path = "http://localhost:5432/SPY"

* -------------------------------------------------------------------
* sqlite://<nohostname>/<path>
    
* where <path> is relative:
* engine = create_engine('sqlite:///Manager.db')
* See: https://docs.sqlalchemy.org/en/13/core/engines.html#postgresql
    
* Unix/Mac - 4 initial slashes in total
* engine = create_engine('sqlite:////absolute/path/to/foo.db')
* -------------------------------------------------------------------

In [17]:
# Import and establish Base for which classes will be constructed 
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

In [18]:
# Import modules to declare columns and column data types
from sqlalchemy import Column, Integer, String, Float

In [19]:
import sys

In [20]:
# .  does connect
engine = create_engine('postgresql://postgres:Roshan2017@localhost:5432/SPY',pool_size=20,max_overflow=-1)
#connection = engine.connect()
conn = engine.connect()
# https://martin-thoma.com/configuration-files-in-python/

drop table Stock_option

In [21]:
#----------------------------------------------------------------
# Create SPY class(es), with its corresponding Table
#----------------------------------------------------------------

class SPY(Base):
    __tablename__ = 'Stock_Option'
    Contract_Name = Column(String(20))
    Bid = Column(Integer, primary_key=True)
    Stocks = Column(Integer)
    Strike = Column(Integer)
    Options = Column(Integer)
    Date=Column(Integer)
    ImpliedVolatility=Column(Integer)
    ClosePrice=Column(Integer)

In [22]:
##
#engine = create_engine('postgresql://postgres:Roshan2017@localhost:5432/SPY',pool_size=20,max_overflow=-1)
# ---------------------------------------------------------------------------------------
###connection = engine.connect()    This was connected to SQLITE which we are not using here!#
#conn = engine.connect()
#  See: https://martin-thoma.com/configuration-files-in-python/

In [23]:
#!/usr/bin/env python
#import databaseconfig as cfg
#connect(cfg.mysql['host'], cfg.mysql['user'], cfg.mysql['password'])

In [24]:
#-------------------------------------------------
# Create Database Connection - Does Connect
# ------------------------------------------------
# Establish Connection
#engine = create_engine("sqlite:///manager.sqlite")
#conn = engine.connect()

In [25]:
# ----------------------------------------------------------------------------------
#  Create specific instances of SPY_Table
# . Make sure you increment the "key" as it cannot be added as a duplicate key!!!!!!!!!!!!!!!!!!!!!!!!!!!
# ----------------------------------------------------------------------------------
table_data = SPY(Contract_Name='call-Alemi-C00009', 
                 Bid=349, 
                 Stocks=350,
                 Strike=320,
                 Options=33.5,
                 Date=20200105,
                 ImpliedVolatility=45,
                 ClosePrice= 324)

In [26]:
# Create Managers and possibly other tables within the database
Base.metadata.create_all(conn)

In [27]:
# To push the objects (Table) made and query the server we use a Session object
from sqlalchemy.orm import Session
session = Session(bind=engine)

In [28]:
# Add "Table" to the current session
session.add(table_data)
# Commit the object to the database
session.commit()

In [29]:
# Query the database and collect all of the stock data in the database
query_list = session.query(SPY)
for bro in query_list:
    print(bro.Contract_Name)
    print(bro.Bid)
    print(bro.Stocks)

call-Alemi-C00006
345
350
call-Alemi-C00007
348
350
call-Alemi-C00009
349
350

In [30]:
#--Import Matplot lib
import numpy as np

import matplotlib
from matplotlib import style
style.use('seaborn')
import matplotlib.pyplot as plt

In [31]:
# .  Which Contract occurs most
# pd.read_csv("../sql_Challenge/data-1578190445297.csv")
# . The above CSV contained a histogram

In [32]:
#input_df = pd.read_csv("../sql_Challenge/data-1578190445297.csv", delimiter=',', names = ['last_name', 'counter'])
input_df = pd.read_csv("../etl_Challenge/options_data.csv",nrows=10)
input_df.head(10)

,Contract Name,Bid,Strike,Last Price,Last Trade Date,Implied Volatility,DateTime
0,SPY200129C00280000,47.87,280.0,42.65,2020-01-06 12:15PM EST,135.16%,2020-01-06 12:15PM EST
1,SPY200129C00300000,27.92,300.0,27.00,2020-01-27 3:42PM EST,83.20%,2020-01-27 3:42PM EST
2,SPY200129C00301000,26.93,301.0,22.96,2020-01-27 3:41PM EST,81.84%,2020-01-27 3:41PM EST
3,SPY200129C00302000,25.93,302.0,26.40,2020-01-10 9:37AM EST,78.52%,2020-01-10 9:37AM EST
4,SPY200129C00303000,24.92,303.0,23.84,2020-01-28 1:05PM EST,75.39%,2020-01-28 1:05PM EST
5,SPY200129C00305000,22.95,305.0,21.44,2020-01-28 10:25AM EST,72.85%,2020-01-28 10:25AM EST
6,SPY200129C00308000,19.92,308.0,18.84,2020-01-24 2:58PM EST,61.91%,2020-01-24 2:58PM EST
7,SPY200129C00309000,18.92,309.0,15.69,2020-01-27 9:50AM EST,59.18%,2020-01-27 9:50AM EST
8,SPY200129C00310000,17.95,310.0,17.75,2020-01-29 10:57AM EST,58.98%,2020-01-29 10:57AM EST
9,SPY200129C00312000,15.93,312.0,14.56,2020-01-21 3:36PM EST,51.76%,2020-01-21 3:36PM EST

In [33]:
# --------------------------------------------------------------------------
# .             This command scrapes the Options Data set and by passes the CSV!
# --------------------------------------------------------------------------
options=pd.read_html("https://finance.yahoo.com/quote/SPY/options?p=SPY")
print(options)

[         Contract Name         Last Trade Date  Strike  Last Price    Bid  \
0   SPY200203C00270000   2020-01-31 3:46PM EST   270.0       51.70  52.15
1   SPY200203C00275000  2020-01-03 12:36PM EST   275.0       49.01  47.15
2   SPY200203C00280000  2020-01-06 12:03PM EST   280.0       42.76  42.16
3   SPY200203C00285000  2020-01-06 12:01PM EST   285.0       37.82  37.17
4   SPY200203C00290000   2020-01-31 3:39PM EST   290.0       31.18  32.19
5   SPY200203C00296000  2020-01-30 10:26AM EST   296.0       26.25  26.21
6   SPY200203C00300000   2020-01-31 3:40PM EST   300.0       21.19  22.23
7   SPY200203C00302000  2020-01-30 11:05PM EST   302.0       20.47  20.25
8   SPY200203C00305000  2020-01-28 10:08AM EST   305.0       18.73  17.28
9   SPY200203C00307000   2020-01-03 3:50PM EST   307.0       18.45  15.31
10  SPY200203C00309000   2020-01-27 9:43AM EST   309.0       13.05  13.35
11  SPY200203C00310000   2020-01-31 4:10PM EST   310.0       12.45  12.39
12  SPY200203C00311000   2020-01-31 4:00PM EST   311.0       11.16  11.43
13  SPY200203C00312000   2020-01-31 3:44PM EST   312.0       10.11  10.48
14  SPY200203C00313000   2020-01-30 3:39PM EST   313.0       11.20   9.54
15  SPY200203C00314000   2020-01-31 4:12PM EST   314.0        8.63   8.61
16  SPY200203C00315000   2020-01-31 4:01PM EST   315.0        7.60   7.71
17  SPY200203C00316000   2020-01-31 3:58PM EST   316.0        6.56   6.81
18  SPY200203C00317000   2020-01-31 4:12PM EST   317.0        5.94   5.94
19  SPY200203C00318000   2020-01-31 3:59PM EST   318.0        4.54   5.11
20  SPY200203C00319000   2020-01-31 4:14PM EST   319.0        4.37   4.31
21  SPY200203C00320000   2020-01-31 4:13PM EST   320.0        3.59   3.53
22  SPY200203C00321000   2020-01-31 4:14PM EST   321.0        2.81   2.82
23  SPY200203C00322000   2020-01-31 4:14PM EST   322.0        2.20   2.16
24  SPY200203C00323000   2020-01-31 4:14PM EST   323.0        1.59   1.57
25  SPY200203C00324000   2020-01-31 4:14PM EST   324.0        1.10   1.06
26  SPY200203C00325000   2020-01-31 4:14PM EST   325.0        0.69   0.66
27  SPY200203C00326000   2020-01-31 4:14PM EST   326.0        0.39   0.38
28  SPY200203C00327000   2020-01-31 4:14PM EST   327.0        0.20   0.20
29  SPY200203C00327500   2020-01-31 4:14PM EST   327.5        0.15   0.15
30  SPY200203C00328000   2020-01-31 4:14PM EST   328.0        0.11   0.10
31  SPY200203C00328500   2020-01-31 4:10PM EST   328.5        0.08   0.06
32  SPY200203C00329000   2020-01-31 4:13PM EST   329.0        0.05   0.05
33  SPY200203C00329500   2020-01-31 4:14PM EST   329.5        0.03   0.03
34  SPY200203C00330000   2020-01-31 4:14PM EST   330.0        0.02   0.02
35  SPY200203C00330500   2020-01-31 3:57PM EST   330.5        0.02   0.01
36  SPY200203C00331000   2020-01-31 3:59PM EST   331.0        0.01   0.00
37  SPY200203C00331500   2020-01-31 4:11PM EST   331.5        0.01   0.00
38  SPY200203C00332000   2020-01-31 4:14PM EST   332.0        0.02   0.01
39  SPY200203C00332500   2020-01-31 3:26PM EST   332.5        0.01   0.00
40  SPY200203C00333000   2020-01-31 4:11PM EST   333.0        0.01   0.01
41  SPY200203C00333500   2020-01-31 3:28PM EST   333.5        0.01   0.00
42  SPY200203C00334000   2020-01-31 1:44PM EST   334.0        0.01   0.00
43  SPY200203C00334500   2020-01-30 4:05PM EST   334.5        0.01   0.00
44  SPY200203C00335000   2020-01-31 3:29PM EST   335.0        0.01   0.02
45  SPY200203C00336000   2020-01-31 3:40PM EST   336.0        0.01   0.00
46  SPY200203C00337000   2020-01-30 2:09PM EST   337.0        0.01   0.00
47  SPY200203C00338000   2020-01-29 2:36PM EST   338.0        0.02   0.00
48  SPY200203C00339000   2020-01-28 2:20PM EST   339.0        0.01   0.06
49  SPY200203C00340000   2020-01-28 2:48PM EST   340.0        0.01   0.01
50  SPY200203C00341000   2020-01-23 3:59PM EST   341.0        0.01   0.01
51  SPY200203C00342000  2020-01-29 11:40AM EST   342.0        0.01   0.01
52  SPY200203C00343000   2020-01-24 3:20PM EST   343.0        0.01   0.01
53  SPY200203C00344000   2020-01-22 3:40PM EST   344.0        0.01   0.01
54  SPY200203C00345000   2020-01-22 9:30AM EST   345.0        0.03   0.00
55  SPY200203C00346000   2020-01-21 2:05PM EST   346.0        0.01      -
56  SPY200203C00348000   2020-01-21 9:30AM EST   348.0        0.01   0.00
57  SPY200203C00350000  2020-01-24 12:47PM EST   350.0        0.01   0.00
58  SPY200203C00355000   2020-01-02 1:19PM EST   355.0        0.01   0.00

      Ask  Change % Change Volume Open Interest Implied Volatility
0   52.42  -10.11  -16.36%     80             0            113.72%
1   47.42    0.00        -      2             0            103.86%
2   42.43    0.00        -      -             0             94.43%
3   37.43    0.00        -      -             0             84.77%
4   32.44   -5.81  -15.71%      1             0             75.39%
5   26.46   -2.80   -9.64%      -             -             63.97%
6   22.48   -8.73  -29.18%      8             0             56.40%
7   20.50   -1.68   -7.58%      2             0             52.73%
8   17.53   -2.28  -10.85%      1             0             49.41%
9   15.56    0.00        -      1             0             45.53%
10  13.60   -2.93  -18.34%     45             0             41.68%
11  12.62   -6.03  -32.63%     68             0             39.70%
12  11.64   -3.16  -22.07%     64             0             37.65%
13  10.69   -5.73  -36.17%     89             0             35.96%
14   9.74   -2.50  -18.25%     27             0             34.18%
15   8.79   -1.66  -16.13%    196             0             32.30%
16   7.81   -2.87  -27.41%    280             0             29.96%
17   6.92   -4.14  -38.69%    146             0             28.54%
18   6.05   -2.54  -29.95%    325             0             27.12%
19   5.20   -3.35  -42.46%    990             0             25.66%
20   4.39   -2.62  -37.48%   1030             0             24.32%
21   3.62   -4.39  -55.01%   6286             0             22.97%
22   2.89   -4.87  -63.41%   5805             0             21.58%
23   2.21   -3.61  -62.13%  17278             0             20.12%
24   1.62   -3.75  -70.22%  27483             0             18.85%
25   1.10   -3.52  -76.19%  49374             0             17.44%
26   0.69   -3.10  -81.79%  46029             0             16.19%
27   0.39   -2.82  -87.85%  43170             0             15.02%
28   0.22   -2.23  -91.77%  37802             0             14.45%
29   0.16   -1.93  -92.79%   6256             0             14.21%
30   0.12   -1.63  -93.68%  15987             0             14.11%
31   0.08   -1.41  -94.63%   9538             0             13.77%
32   0.06   -1.15  -95.83%   9625             0             13.77%
33   0.04   -0.91  -96.81%   3295             0             13.58%
34   0.03   -0.72  -97.30%  14216             0             13.67%
35   0.02   -0.54  -96.43%   1351             0             13.48%
36   0.01   -0.40  -97.56%   3522             0             12.89%
37   0.01   -0.28  -96.55%   3338             0             13.67%
38   0.02   -0.19  -90.48%   1903             0             15.43%
39   0.01   -0.12  -92.31%   1144             0             14.84%
40   0.02   -0.08  -88.89%   2137             0             16.80%
41   0.01   -0.04  -80.00%   3853             0             16.02%
42   0.01   -0.02  -66.67%    297             0             16.41%
43   0.01   -0.01  -50.00%     88             0             17.19%
44   0.01    0.00        -     34             0             17.58%
45   0.01   -0.01  -50.00%     15             0             18.75%
46   0.01    0.00        -     21             0             19.92%
47   0.01    0.00        -    236             0             21.09%
48   0.01    0.00        -     37             0             22.27%
49   0.01    0.00        -    117             0             23.44%
50   0.01    0.00        -    114             0             24.22%
51   0.01    0.00        -      1             0             25.78%
52   0.01    0.00        -      1             0             26.56%
53   0.01    0.00        -     50             0             27.74%
54   0.01    0.00        -      2             0             28.91%
55   0.01    0.00        -      -             0             29.69%
56   0.01    0.00        -      5             0             32.03%
57   0.01    0.00        -     25             0             34.38%
58   0.01    0.00        -     50             0             39.06%  ,          Contract Name         Last Trade Date  Strike  Last Price    Bid  \
0   SPY200203P00270000  2020-01-30 10:44AM EST   270.0        0.01   0.00
1   SPY200203P00275000   2020-01-31 4:12PM EST   275.0        0.01   0.00
2   SPY200203P00280000   2020-01-31 4:14PM EST   280.0        0.01   0.00
3   SPY200203P00285000   2020-01-31 3:53PM EST   285.0        0.02   0.01
4   SPY200203P00290000   2020-01-31 3:58PM EST   290.0        0.03   0.02
..                 ...                     ...     ...         ...    ...
60  SPY200203P00340000   2020-01-30 3:24PM EST   340.0       13.45  17.60
61  SPY200203P00341000   2020-01-24 9:48AM EST   341.0        9.98  18.61
62  SPY200203P00342000   2020-01-17 3:30PM EST   342.0       10.29  19.60
63  SPY200203P00350000   2020-01-08 9:53AM EST   350.0       26.15  27.60
64  SPY200203P00355000   2020-01-27 3:53PM EST   355.0       31.25  32.60

      Ask  Change  % Change Volume Open Interest Implied Volatility
0    0.01    0.00         -      2             0             62.50%
1    0.01    0.00         -  37720             0             56.25%
2    0.01    0.00         -  24500             0             50.00%
3    0.02    0.01  +100.00%   4812             0             50.00%
4    0.03    0.01   +50.00%    704             0             46.88%
..    ...     ...       ...    ...           ...                ...
60  17.86    0.00         -      1             0              0.00%
61  18.86    0.00         -      -             -              0.00%
62  19.86    0.00         -      -             -              0.00%
63  27.86    0.00         -     10             0              0.00%
64  32.87    0.00         -      -             0              0.00%

[65 rows x 11 columns]]

In [34]:
options[0].head()

,Contract Name,Last Trade Date,Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility
0,SPY200203C00270000,2020-01-31 3:46PM EST,270.0,51.70,52.15,52.42,-10.11,-16.36%,80,0,113.72%
1,SPY200203C00275000,2020-01-03 12:36PM EST,275.0,49.01,47.15,47.42,0.00,-,2,0,103.86%
2,SPY200203C00280000,2020-01-06 12:03PM EST,280.0,42.76,42.16,42.43,0.00,-,-,0,94.43%
3,SPY200203C00285000,2020-01-06 12:01PM EST,285.0,37.82,37.17,37.43,0.00,-,-,0,84.77%
4,SPY200203C00290000,2020-01-31 3:39PM EST,290.0,31.18,32.19,32.44,-5.81,-15.71%,1,0,75.39%

In [35]:
options_df=options[0][["Contract Name","Bid","Strike","Last Price", "Last Trade Date", "Implied Volatility"]]
#Bid=options[0][["Bid"]]
#Bid
options_df.head()

,Contract Name,Bid,Strike,Last Price,Last Trade Date,Implied Volatility
0,SPY200203C00270000,52.15,270.0,51.70,2020-01-31 3:46PM EST,113.72%
1,SPY200203C00275000,47.15,275.0,49.01,2020-01-03 12:36PM EST,103.86%
2,SPY200203C00280000,42.16,280.0,42.76,2020-01-06 12:03PM EST,94.43%
3,SPY200203C00285000,37.17,285.0,37.82,2020-01-06 12:01PM EST,84.77%
4,SPY200203C00290000,32.19,290.0,31.18,2020-01-31 3:39PM EST,75.39%

In [36]:
options_df["DateTime"] = options_df["Last Trade Date"]
#options_df["DateTime"] = options_df["Last Trade Date"]
DateTime.head()

/Users/piruzalemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

NameError: name 'DateTime' is not defined

In [37]:
#df = options_df.DateTime.str.split(expand=True)   
#df.columns = ['Date', 'Time', 'place']

In [38]:
#options_df = options_df.DateTime.str.split(expand=True)   
#options_df

In [39]:
df.head()

NameError: name 'df' is not defined

In [40]:
Options=pd.merge(options_df, df, on='Date', how='left')
Options

NameError: name 'df' is not defined

In [41]:

stocks=pd.read_csv("../ETL_Challenge/spy.csv")
stocks.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-01-29,263.920013,264.549988,262.480011,263.410004,258.514801,66136300
1,2019-01-30,265.100006,268.519989,264.250000,267.579987,262.607300,92473700
2,2019-01-31,267.510010,270.470001,267.269989,269.929993,264.913605,104012100
3,2019-02-01,270.149994,271.200012,269.179993,270.059998,265.041229,85782500
4,2019-02-04,270.109985,272.029999,269.359985,271.959991,266.905884,60744800

In [42]:
options_df = options_df.drop_duplicates(subset=['Date'], keep='first')

KeyError: Index(['Date'], dtype='object')

In [43]:
stockOption=pd.merge(options_df, stocks, on='Date', how='left')
stockOption

KeyError: 'Date'

In [44]:
options_df['Date'] = df["Date"]

NameError: name 'df' is not defined

In [45]:

# Set x axis and tick locations
x_axis = np.arange(len(input_df))
tick_locations = [value for value in x_axis]
# Create a list indicating where to write x labels and set figure size to adjust for space
plt.figure(figsize=(20,3))
plt.bar(x_axis, input_df["count"], color='b', alpha=0.5, align="center")
plt.xticks(tick_locations, input_df["Contract_name"], rotation="vertical")
# Set x and y limits
plt.xlim(-0.75, len(x_axis))
plt.ylim(215, max(input_df["count"])+10)
# Set a Title and labels
plt.title("Top 10 Repeated Frequencies of Last-Names in Employees file")
plt.xlabel("Last Names")
plt.ylabel("Frequency of occurance")
plt.tight_layout()
plt.savefig("../sql_challenge/lastName_Freq.png")
plt.show()

KeyError: 'count'

In [46]:
options_df.head()

,Contract Name,Bid,Strike,Last Price,Last Trade Date,Implied Volatility,DateTime
0,SPY200203C00270000,52.15,270.0,51.70,2020-01-31 3:46PM EST,113.72%,2020-01-31 3:46PM EST
1,SPY200203C00275000,47.15,275.0,49.01,2020-01-03 12:36PM EST,103.86%,2020-01-03 12:36PM EST
2,SPY200203C00280000,42.16,280.0,42.76,2020-01-06 12:03PM EST,94.43%,2020-01-06 12:03PM EST
3,SPY200203C00285000,37.17,285.0,37.82,2020-01-06 12:01PM EST,84.77%,2020-01-06 12:01PM EST
4,SPY200203C00290000,32.19,290.0,31.18,2020-01-31 3:39PM EST,75.39%,2020-01-31 3:39PM EST

In [47]:
#plt.tight_layout()
#plt.savefig("../sql_challenge/lastName_Freq.png")
#plt.show()